In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('JEOPARDY_CSV.csv')
data.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 216930 entries, 0 to 216929
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Show Number  216930 non-null  int64
 1    Air Date    216930 non-null  str
 2    Round       216930 non-null  str
 3    Category    216930 non-null  str
 4    Value       213296 non-null  str
 5    Question    216930 non-null  str
 6    Answer      216927 non-null  str
dtypes: int64(1), str(6)
memory usage: 11.6 MB

In [4]:
X = data[[' Question']]
X.head()

                                            Question
0  For the last 8 years of his life, Galileo was ...
1  No. 2: 1912 Olympian; football star at Carlisl...
2  The city of Yuma in this state has a record av...
3  In 1963, live on "The Art Linkletter Show", th...
4  Signer of the Dec. of Indep., framer of the Co...

In [5]:
with open('stopwords.txt') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 "can't",
 'cannot',
 'could',
 "couldn't",
 'did',
 "didn't",
 'do',
 'does',
 "doesn't",
 'doing',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 "hadn't",
 'has',
 "hasn't",
 'have',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 "here's",
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 "how's",
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 "let's",
 'me',
 'more',
 'most',
 "mustn't",
 'my',
 'myself',
 'no',
 'nor',
 'not',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'same',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "shouldn't",
 'so',
 'some',
 'such',
 'than',
 'that',
 "that's",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 "there's",
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 'very',
 'was',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 "weren't",
 'what',
 "what's",
 'when',
 "when's",
 'where',
 "where's",
 'which',
 'while',
 'who',
 "who's",
 'whom',
 'why',
 "why's",
 'with',
 "won't",
 'would',
 "wouldn't",
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves',
 '',
 'a',
 'able',
 'about',
 'above',
 'abst',
 'accordance',
 'according',
 'accordingly',
 'across',
 'act',
 'actually',
 'added',
 'adj',
 'affected',
 'affecting',
 'affects',
 'after',
 'afterwards',
 'again',
 'against',
 'ah',
 'all',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'announce',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apparently',
 'approximately',
 'are',
 'aren',
 'arent',
 'arise',
 'around',
 'as',
 'aside',
 'ask',
 'asking',
 'at',
 'auth',
 'available',
 'away',
 'awfully',
 'b',
 'back',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'between',
 'beyond',
 'biol',
 'both',
 'brief',
 'briefly',
 'but',
 'by',
 'c',
 'ca',
 'came',
 'can',
 'cannot',
 "can't",
 'cause',
 'causes',
 'certain',
 'certainly',
 'co',
 'com',
 'come',
 'comes',
 'contain',
 'containing',
 'contains',
 'could',
 'couldnt',
 'd',
 'date',
 'did',
 "didn't",
 'different',
 'do',
 'does',
 "doesn't",
 'doing',
 'done',
 "don't",
 'down',
 'downwards',
 'due',
 'during',
 'e',
 'each',
 'ed',
 'edu',
 'effect',
 'eg',
 'eight',
 'eighty',
 'either',
 'else',
 'elsewhere',
 'end',
 'ending',
 'enough',
 'especially',
 'et',
 'et-al',
 'etc',
 'even',
 'ever',
 'every',
 'everybody',
 'everyone',
 'everything',
 'everywhere',
 'ex',
 'except',
 'f',
 'far',
 'few',
 'ff',
 'fifth',
 'first',
 'five',
 'fix',
 'followed',
 'following',
 'follows',
 'for',
 'former',
 'formerly',
 'forth',
 'found',
 'four',
 'from',
 'further',
 'furthermore',
 'g',
 'gave',
 'get',
 'gets',
 'getting',
 'give',
 'given',
 'gives',
 'giving',
 'go',
 'goes',
 'gone',
 'got',
 'gotten',
 'h',
 'had',
 'happens',
 'hardly',
 'has',
 "hasn't",
 'have',
 "haven't",
 'having',
 'he',
 'hed',
 'hence',
 'her',
 'here',
 'hereafter',
 'hereby',
 'herein',
 'heres',
 'hereupon',
 'hers',
 'herself',
 'hes',
 'hi',
 'hid',
 'him',
 'himself',
 'his',
 'hither',
 'home',
 'how',
 'howbeit',
 'however',
 'hundred',
 'i',
 'id',
 'ie',
 'if',
 "i'll",
 'im',
 'immediate',
 'immediately',
 'importance',
 'important',
 'in',
 'inc',
 'indeed',
 'index',
 'information',
 'instead',
 'into',
 'invention',
 'inward',
 'is',
 "isn't",
 'it',
 'itd',
 "it'll",
 'its',
 'itself',
 "i've",
 'j',
 'just',
 'k',
 'keep',
 'keeps',
 'kept',
 'kg',
 'km',
 'know',
 'known',
 'knows',
 'l',
 'largely',
 'last',
 'lately',
 'later',
 'latter',
 'latterly',
 'least',
 'less',
 'lest',
 'let',
 'lets',
 'like',
 'liked',
 'likely',
 'line',
 'little',
 "'ll",
 'look',
 'looking',
 'looks',
 'ltd',
 'm',
 'made',
 'mainly',
 'make',
 'makes',
 'many',
 'may',
 'maybe',
 'me',
 'mean',
 'means',
 'meantime',
 'meanwhile',
 'merely',
 'mg',
 'might',
 'million',
 'miss',
 'ml',
 'more',
 'moreover',
 'most',
 'mostly',
 'mr',
 'mrs',
 'much',
 'mug',
 'must',
 'my',
 'myself',
 'n',
 'na',
 'name',
 'namely',
 'nay',
 'nd',
 'near',
 'nearly',
 'necessarily',
 'necessary',
 'need',
 'needs',
 'neither',
 'never',
 'nevertheless',
 'new',
 'next',
 'nine',
 'ninety',
 'no',
 'nobody',
 'non',
 'none',
 'nonetheless',
 'noone',
 'nor',
 'normally',
 'nos',
 'not',
 'noted',
 'nothing',
 'now',
 'nowhere',
 'o',
 'obtain',
 'obtained',
 'obviously',
 'of',
 'off',
 'often',
 'oh',
 'ok',
 'okay',
 'old',
 'omitted',
 'on',
 'once',
 'one',
 'ones',
 'only',
 'onto',
 'or',
 'ord',
 'other',
 'others',
 'otherwise',
 'ought',
 'our',
 'ours',
 'ourselves',
 'out',
 'outside',
 'over',
 'overall',
 'owing',
 'own',
 'p',
 'page',
 'pages',
 'part',
 'particular',
 'particularly',
 'past',
 'per',
 'perhaps',
 'placed',
 'please',
 'plus',
 'poorly',
 'possible',
 'possibly',
 'potentially',
 'pp',
 'predominantly',
 'present',
 'previously',
 'primarily',
 'probably',
 'promptly',
 'proud',
 'provides',
 'put',
 'q',
 'que',
 'quickly',
 'quite',
 'qv',
 'r',
 'ran',
 'rather',
 'rd',
 're',
 'readily',
 'really',
 'recent',
 'recently',
 'ref',
 'refs',
 'regarding',
 'regardless',
 'regards',
 'related',
 'relatively',
 'research',
 'respectively',
 'resulted',
 'resulting',
 'results',
 'right',
 'run',
 's',
 'said',
 'same',
 'saw',
 'say',
 'saying',
 'says',
 'sec',
 'section',
 'see',
 'seeing',
 'seem',
 'seemed',
 'seeming',
 'seems',
 'seen',
 'self',
 'selves',
 'sent',
 'seven',
 'several',
 'shall',
 'she',
 'shed',
 "she'll",
 'shes',
 'should',
 "shouldn't",
 'show',
 'showed',
 'shown',
 'showns',
 'shows',
 'significant',
 'significantly',
 'similar',
 'similarly',
 'since',
 'six',
 'slightly',
 'so',
 'some',
 'somebody',
 'somehow',
 'someone',
 'somethan',
 'something',
 'sometime',
 'sometimes',
 'somewhat',
 'somewhere',
 'soon',
 'sorry',
 'specifically',
 'specified',
 'specify',
 'specifying',
 'still',
 'stop',
 'strongly',
 'sub',
 'substantially',
 'successfully',
 'such',
 'sufficiently',
 'suggest',
 'sup',
 'sure',
 't',
 'take',
 'taken',
 'taking',
 'tell',
 'tends',
 'th',
 'than',
 'thank',
 'thanks',
 'thanx',
 'that',
 "that'll",
 'thats',
 "that've",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'thence',
 'there',
 'thereafter',
 'thereby',
 'thered',
 'therefore',
 'therein',
 "there'll",
 'thereof',
 'therere',
 'theres',
 'thereto',
 'thereupon',
 "there've",
 'these',
 'they',
 'theyd',
 "they'll",
 'theyre',
 "they've",
 'think',
 'this',
 'those',
 'thou',
 'though',
 'thoughh',
 'thousand',
 'throug',
 'through',
 'throughout',
 'thru',
 'thus',
 'til',
 'tip',
 'to',
 'together',
 'too',
 'took',
 'toward',
 'towards',
 'tried',
 'tries',
 'truly',
 'try',
 'trying',
 'ts',
 'twice',
 'two',
 'u',
 'un',
 'under',
 'unfortunately',
 'unless',
 'unlike',
 'unlikely',
 'until',
 'unto',
 'up',
 'upon',
 'ups',
 'us',
 'use',
 'used',
 'useful',
 'usefully',
 'usefulness',
 'uses',
 'using',
 'usually',
 'v',
 'value',
 'various',
 "'ve",
 'very',
 'via',
 'viz',
 'vol',
 'vols',
 'vs',
 'w',
 'want',
 'wants',
 'was',
 'wasnt',
 'way',
 'we',
 'wed',
 'welcome',
 "we'll",
 'went',
 'were',
 'werent',
 "we've",
 'what',
 'whatever',
 "what'll",
 'whats',
 'when',
 'whence',
 'whenever',
 'where',
 'whereafter',
 'whereas',
 'whereby',
 'wherein',
 'wheres',
 'whereupon',
 'wherever',
 'whether',
 'which',
 'while',
 'whim',
 'whither',
 'who',
 'whod',
 'whoever',
 'whole',
 "who'll",
 'whom',
 'whomever',
 'whos',
 'whose',
 'why',
 'widely',
 'willing',
 'wish',
 'with',
 'within',
 'without',
 'wont',
 'words',
 'world',
 'would',
 'wouldnt',
 'www',
 'x',
 'y',
 'yes',
 'yet',
 'you',
 'youd',
 "you'll",
 'your',
 'youre',
 'yours',
 'yourself',
 'yourselves',
 "you've",
 'z',
 'zero',
 "'ll",
 "'tis",
 "'twas",
 "'ve",
 '10',
 '39',
 'a',
 "a's",
 'able',
 'ableabout',
 'about',
 'above',
 'abroad',
 'abst',
 'accordance',
 'according',
 'accordingly',
 'across',
 'act',
 'actually',
 'ad',
 'added',
 'adj',
 'adopted',
 'ae',
 'af',
 'affected',
 'affecting',
 'affects',
 'after',
 'afterwards',
 'ag',
 'again',
 'against',
 'ago',
 'ah',
 'ahead',
 'ai',
 "ain't",
 'aint',
 'al',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'alongside',
 'already',
 'also',
 'although',
 'always',
 'am',
 'amid',
 'amidst',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'an',
 'and',
 'announce',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ao',
 'apart',
 'apparently',
 'appear',
 'appreciate',
 'appropriate',
 'approximately',
 'aq',
 'ar',
 'are',
 'area',
 'areas',
 'aren',
 "aren't",
 'arent',
 'arise',
 'around',
 'arpa',
 'as',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'associated',
 'at',
 'au',
 'auth',
 'available',
 'aw',
 'away',
 'awfully',
 'az',
 'b',
 'ba',
 'back',
 'backed',
 'backing',
 'backs',
 'backward',
 'backwards',
 'bb',
 'bd',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'began',
 'begin',
 'beginning',
 'beginnings',
 'begins',
 'behind',
 'being',
 'beings',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'bf',
 'bg',
 'bh',
 'bi',
 'big',
 'bill',
 'billion',
 'biol',
 'bj',
 'bm',
 'bn',
 'bo',
 'both',
 'bottom',
 'br',
 'brief',
 'briefly',
 'bs',
 ...]

In [6]:
import nltk
import re
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize


nltk.download('punkt_tab')     
nltk.download('stopwords')

stopwords = set(stopwords.words('english'))

# ' Question'
dataset = pd.DataFrame(columns=['title_body'])

for index, row in X.iterrows():
    title_body_tokenized = word_tokenize(row[' Question'])
    title_body_tokenized_filtered = [w.lower() for w in title_body_tokenized if w.lower() not in stopwords]
    
    # ( raw string)
    s = re.sub(r'[^\w\s]', '', ' '.join(title_body_tokenized_filtered))
    s = re.sub(r"\d+", "", s)
    
    dataset.loc[index] = {'title_body': s}

[nltk_data] Downloading package punkt_tab to /Users/hadis/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/hadis/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
dataset

                                               title_body
0       last  years life  galileo house arrest espousi...
1           olympian  football star carlisle indian sc...
2       city yuma state record average  hours sunshine...
3         live  art linkletter show   company served b...
4       signer dec indep  framer constitution mass  se...
...                                                   ...
216925  puccini opera turns solution  riddles posed he...
216926  north america term properly applied  species c...
216927  penny lane   hellraiser  grew  barber shaves a...
216928  ft sill  okla made plea  arizona land  home  f...
216929  silent movie title includes last name th c sta...

[216930 rows x 1 columns]

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [10]:
X = vectorizer.transform(dataset['title_body'])

In [11]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1753129 stored elements and shape (216930, 94108)>

In [12]:
import umap
reducer = umap.UMAP(n_components=1000)

ModuleNotFoundError: No module named 'umap'

In [ ]:
X_reduced = reducer.fit_transform(X)

In [ ]:
import numpy as np
np.shape(X_reduced)

In [ ]:
import pickle
with open('X_reduced.masoud', 'wb') as f:
    pickle.dump(X_reduced, f)

In [ ]:
from sklearn.cluster import MeanShift

In [ ]:
msh = MeanShift()
msh.fit(X_reduced)

In [ ]:
msh.inertia_

In [74]:
from sklearn.metrics import silhouette_score

In [23]:
silhouette_score(X, kmeans.labels_)

0.006985732156319591

In [77]:
dataset['Cluster'] = kmeans.labels_

In [78]:
dataset[dataset['Cluster'] == 1]

                                               title_body  Cluster
54       imbroglio  french agents demanded huge bribe ...        1
99      mighty leap    david mosely set us  record event         1
169      onetime vp compiled  manual parliamentary pra...        1
227     david bengurion us  empire exiled zionists pal...        1
246     descriptive nickname us flag coined francis sc...        1
...                                                   ...      ...
216694    age   joined us women s team  cup   olympic ...        1
216826                  lbj    american  us  senator             1
216836   olympics  german team gold equestrian event  ...        1
216871  us coin likeness president coin based photo ma...        1
216877    us potash process  signed washington  jefferson        1

[4496 rows x 2 columns]

In [79]:
from collections import Counter

In [87]:
Counter(" ".join(dataset[dataset['Cluster'] == 5]["title_body"]).split()).most_common(20)

[('war', 2180),
 ('latin', 1406),
 ('s', 936),
 ('civil', 347),
 ('word', 256),
 ('country', 142),
 ('meaning', 116),
 ('battle', 115),
 ('american', 95),
 ('term', 94),
 ('named', 78),
 ('peace', 76),
 ('type', 75),
 ('president', 73),
 ('british', 72),
 ('city', 66),
 ('revolutionary', 64),
 ('fought', 59),
 ('phrase', 59),
 ('served', 58)]